version: '3.6'
services:
  graphql-engine:
    image: 'hasura/graphql-engine:v2.37.0'
    ports:
      - '8090:8080'
    restart: always
    environment:
      HASURA_GRAPHQL_METADATA_DATABASE_URL: 'postgres://postgres:GB2WF78eZkgGkAcK4VbTgUI9ycYU7or9H83xJDmK5MtM1InGIFja4IL47P3qarnJ@isk4w4s:5432/postgres'
      PG_DATABASE_URL: 'postgres://postgres:GB2WF78eZkgGkAcK4VbTgUI9ycYU7or9H83xJDmK5MtM1InGIFja4IL47P3qarnJ@isk4w4s:5432/postgres'
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true'
      HASURA_GRAPHQL_DEV_MODE: 'true'
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: 'startup, http-log, webhook-log, websocket-log, query-log'
      HASURA_GRAPHQL_METADATA_DEFAULTS: '{"backend_configs":{"dataconnector":{"athena":{"uri":"http://data-connector-agent:8091/api/v1/athena"},"mariadb":{"uri":"http://data-connector-agent:8091/api/v1/mariadb"},"mysql8":{"uri":"http://data-connector-agent:8091/api/v1/mysql"},"oracle":{"uri":"http://data-connector-agent:8091/api/v1/oracle"},"snowflake":{"uri":"http://data-connector-agent:8091/api/v1/snowflake"}}}}'
    depends_on:
      data-connector-agent:
        condition: service_healthy
  data-connector-agent:
    image: 'hasura/graphql-data-connector:v2.37.0'
    restart: always
    ports:
      - '8091:8081'
    environment:
      QUARKUS_LOG_LEVEL: ERROR
      QUARKUS_OPENTELEMETRY_ENABLED: 'false'
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://localhost:8081/api/v1/athena/health'
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 5s
volumes:
  db_data: null
